"""initial schema + new task/plan fields

Revision ID: a2b29d1f67e4
Revises: 
Create Date: 2025-12-17 23:20:57.054354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2b29d1f67e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_plan_tasks', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'30'"))
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['public_id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depends_on_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reminder_minutes_before', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tasks', ['depends_on_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reminder_minutes_before')
        batch_op.drop_column('recurrence')
        batch_op.drop_column('depends_on_id')

    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('group_plan_tasks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'30'"))

    # ### end Alembic commands ###
